on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '15 3 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: "ghcr.io/${{ github.repository }}"
